name: CD for bootstrap deploy

on:
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  TerraformStateBackend:
    name: Terraform state backend (${{ github.ref_name }})
    runs-on: ubuntu-latest
    if: contains(fromJSON('["dev","homolog","prod"]'), github.ref_name)
    permissions:
      id-token: write
      contents: read

    outputs:
      s3_bucket_name: ${{ steps.deploy.outputs.s3_bucket_name }}
      dynamo_table_name: ${{ steps.deploy.outputs.dynamo_table_name }}
      aws_region: ${{ steps.deploy.outputs.aws_region }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set AWS account and region for branch
        run: |
          case "${{ github.ref_name }}" in
            dev)
              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
              echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV
              ;;
            homolog)
              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOML }}" >> $GITHUB_ENV
              echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV
              ;;
            prod)
              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
              echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Branch não mapeada."
              exit 1
              ;;
          esac

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: github-action-terraform-state-cdk

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r cdk/requirements.txt
        
      - name: Deploy with CDK
        run: |
          cd cdk
          npx aws-cdk@2 synth
          npx aws-cdk@2 deploy --require-approval never
